### ISSUE TITLE
Feature Request: Ignore certain filetypes

### ISSUE THREAD

**Issue by shaun-mathew** [olimorris/persisted.nvim#17]
Sometimes I close Neovim with NvimTree or Trouble open and upon loading the Session, an empty NvimTree buffer and a pane is created to the side. It would be a nice feature if we could ignore certain filetypes when saving sessions.

*Screenshot*
After loading session:
![nvimtree](https://user-images.githubusercontent.com/16690478/183692479-bc5c3108-c723-4272-95a1-a9f5e3070e24.png)

**Comment by olimorris** [comment]
Hey @shaun-mathew. Have you looked at implementing your own custom [callbacks](https://github.com/olimorris/persisted.nvim#callbacks)? I use them to stop `minimap` being recorded into my session.

**Comment by shaun-mathew** [comment]
Yep, I added something like this to my config that gets the job done:
```lua
config = function()
  require("persisted").setup {
    autosave = true,
    before_save = function()
      vim.cmd "NvimTreeClose"
    end,
  }
end

```
I was just wondering if what I suggested would be possible as a sort of convenience method where the user could specify a list of filetypes and before saving the session, the plugin could go around closing all windows with that filetype. Although, I assume it would get a bit messy.

**Comment by olimorris** [comment]
The reason for adding the _callbacks_ was mainly because I was seeing a lot of singular edge cases crop up that if addressed directly in the plugin, would move it further away from being a "simple session management" plugin.

I ultimately see the _callbacks_ as the plugin's admission that it will never be able to cater for everyone's use cases and therefore it should give the user the ability to dictate how it functions for their given workflow.

**Comment by KevinNitroG** [comment]
Hi ouhm 😅 I'm in trouble with this issue. Is there any config that ignores the window and the buffer of nvim-tree? Thank you!
