### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by linduxed** [olimorris/persisted.nvim#84]
### Your Persisted.nvim config

I'm using the totally unchanged sample `minimal.lua`:

```lua
local root = "/tmp/persisted"

-- Set stdpaths to use root dir
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- Bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

vim.opt.sessionoptions = "buffers,curdir,folds,globals,tabpages,winpos,winsize" -- Session options to store in the session

-- Install plugins
local plugins = {
  {
    "olimorris/persisted.nvim",
    opts = {
      -- Your custom config here
    }
  },
  -- Put any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})
```

### Error messages

The following error message can _not_ be seen with the `minimal.lua` configuration, but with my regular `init.lua` (which has _plenty_ more plugins), I also experience a non-zero exit code, and the following error flashes very briefly (had to record my screen to read the text) in the top left of the screen before Neovim quits:

```
nvim: src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle' failed.
```

### What I expect to happen
Neovim quits with a zero as exit code.

### What actually happens
Neovim quits with a non-zero exit code.

### Extra information
I did a `git bisect` to figure out when the issue was introduced, and it seems like the problem (at least for my setup) started in this commit: https://github.com/olimorris/persisted.nvim/commit/774e4d70e9f0092cc6d2850399fa1ccaca78fc5e

### Reproduce the bug

1. Start Neovim (`nvim --clean -u minimal.lua`)
2. `:q`

### Final checks

- [X] I have made sure this issue exists in the latest version of the plugin
- [X] I have tested with the `minimal.lua` config file above and still get the issue
- [X] I have used `SessionSave` to save the session before restarting Neovim and using `SessionLoad`
- [X] I have made sure this is not a duplicate issue

**Comment by tmpm697** [comment]
I got the same issue. `nvim: src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle' failed.` constantly block the UI, I was thougt this is smth due to nvim config somewhere.

**Comment by olimorris** [comment]
...and how is this related to this plugin? The error message suggests a general issue with Neovim

**Comment by tmpm697** [comment]
no idea but this issue only happens if i enable this plugin.

**Comment by olimorris** [comment]
Nothing has changed in this plugin in two weeks so seems odd that this issue is suddenly appearing. I suspect the issue stems from one of the other plugins installed in your config.

Happy to open this issue again if someone can provide a `minimal.lua` file which showcases the issue. I can't resolve an issue if it can't be recreated.

**Comment by tmpm697** [comment]
it happens for long time, this issue happens when you close nvim, the line
```
nvim: src/unix/core.c:147: uv_close: Assertion `!uv__is_closing(handle' failed.
```
splash in screen before nvim exits that make it hard to capture it.

**Comment by olimorris** [comment]
The issue is a Neovim one, as reported [here](https://github.com/neovim/neovim/issues/21856). A lot of people posting workarounds in that issue.

For future reference, the bug report template exists for many reasons:

1. To ensure that the issue is infact an issue; a lot of the time it's a configuration issue for people
2. To make sure I have a baseline to work from when trying to fix the issue
3. To be protective of my time

Neovim is normally really good at spitting out error messages and this suggests it's a big scary internal bug so in the future always worth googling the error message or heading over to the Neovim GitHub repo in case someone else has encountered it and solved it.

**Comment by olimorris** [comment]
Hey @linduxed, my feedback was aimed at @tmpm697; this would be the third time they've submitted an issue without a proper `minimal.lua` file.

Hope you enjoy the plugin.
